spring.application.name=zen-eureka-server
spring.cloud.config.uri=http://localhost:8888
#spring.cloud.config.uri=http://77.68.94.193:8888
server.port=8762



# Mode standalone
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#eureka.instance.hostname=77.68.94.193
#eureka.instance.ip-address=77.68.94.193
#eureka.instance.prefer-ip-address=true
#eureka.instance.non-secure-port=8762
#eureka.client.service-url.defaultZone=http://77.68.94.193:8762/eureka/

####eureka en local##@#######
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
eureka.instance.hostname=127.0.0.1
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.instance.non-secure-port=8762
eureka.client.service-url.defaultZone=http://127.0.0.1:8762/eureka/


# Optimisations
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
